### ISSUE TITLE
Cálculo do IMC

### ISSUE THREAD

**Issue by GuilhermeHorn2** [gbuzzetti/mc656-project#12]
Temos 2 formas:
1 - IMC : (altural,peso) -> Classificação
2 - Porcentagem de Gordura Corporal e no Sexo do Usuário : (%gordura,sexo) -> Classificação

1 - IMC = massa(kg)/altura²(m²) => [IMC] = kg/m²

Classificação Geral do IMC (Tanto para Homens quanto para Mulheres):

Abaixo do peso:
    IMC < 18,5

Peso normal (ou eutrófico):
    IMC entre 18,5 e 24,9

Sobrepeso:
    IMC entre 25 e 29,9

Obesidade Grau I:
    IMC entre 30 e 34,9

Obesidade Grau II (Obesidade Severa):
    IMC entre 35 e 39,9

Obesidade Grau III (Obesidade Mórbida):
    IMC ≥ 40
2 - CLassificação mais precisa usando índice de massa corporal:

Classificação de Gordura Corporal para Homens:

Gordura essencial: 2% a 5%
    Essencial para o funcionamento do corpo. Valores abaixo disso podem ser perigosos para a saúde.

Atleta: 6% a 13%
    Geralmente observado em atletas com alta massa muscular e baixos níveis de gordura.

Boa forma (fitness): 14% a 17%
    Indicativo de um bom nível de condicionamento físico e saúde.

Aceitável: 18% a 24%
    Percentual de gordura saudável, mas com possíveis riscos se não mantido sob controle.

Sobrepeso: 25% a 29%
    Aumento do risco de problemas de saúde como doenças cardíacas e diabetes.

Obesidade: ≥ 30%
    Alto risco de problemas de saúde graves relacionados à gordura corporal excessiva, como diabetes tipo 2, hipertensão e doenças cardiovasculares.
Classificação de Gordura Corporal para Mulheres:

Gordura essencial: 10% a 13%
    Nível mínimo necessário para o funcionamento hormonal e a proteção de órgãos vitais.

Atleta: 14% a 20%
    Observado em mulheres altamente treinadas, como atletas de elite.

Boa forma (fitness): 21% a 24%
    Indica um nível saudável de aptidão física e um bom equilíbrio entre massa muscular e gordura.

Aceitável: 25% a 31%
    Percentual considerado saudável, embora mais alto do que o "fitness".

Sobrepeso: 32% a 39%
    Indica níveis aumentados de gordura corporal, com risco crescente de problemas de saúde.

Obesidade: ≥ 40%
    Percentual elevado de gordura, associado a um risco muito alto de complicações graves de saúde, como doenças  metabólicas e cardíacas.

*Importante lembrar de checar se o usuário fornesceu os dados nescessários para calcular cada classificação

**Comment by gbuzzetti** [comment]
Feature merged successfully
