### ISSUE TITLE
Calculo de calorias diarias

### ISSUE THREAD

**Issue by elton-aq** [gbuzzetti/mc656-project#6]
Implementar calculo de calorias recomendadas diariamente dado pelo **GCD** (Gasto Calorico total Diario) usando a Equação de Harris-Benedict:

**Passo 1 - calcular TMB (Taxa de Metabolimso Basal):**
- Para homens = 88,36+(13,4×peso em kg)+(4,8×altura em cm)−(5,7×idade em anos)
- Para Mulheres = 447,6+(9,2×peso em kg)+(3,1×altura em cm)−(4,3×idade em anos)

**Passo 2 - Ajustar nivel de atividade fisica:**
- Sedentário (pouca ou nenhuma atividade física): TMB × 1,2
- Levemente ativo (exercício leve ou esportes 1-3 dias por semana): TMB × 1,375
- Moderadamente ativo (exercício moderado ou esportes 3-5 dias por semana): TMB × 1,55
- Altamente ativo (exercício intenso ou esportes 6-7 dias por semana): TMB × 1,725
- Muito ativo (exercício muito intenso, trabalho físico ou treino profissional): TMB × 1,9 

**Passo 3 - Calcular GCD:**

GCD = TMB × Ajuste

**Comment by isaacdono** [comment]
Feature merged successfully.
